[package]
name = "spirv-to-dxil-sys"
version = "0.1.1-beta.1"
edition = "2021"
description = "Raw bindings to spirv-to-dxil"
license = "MIT"
repository = "https://github.com/SnowflakePowered/spirv-to-dxil-rs"
keywords = ["SPIR-V", "DXIL"]

[lib]

[build-dependencies]
bindgen = "0.63.0"
cmake = "0.1"

[features]
included-bindings = []

[package.metadata.docs.rs]
targets = []
features = ["included-bindings"]
