[package]
name = "spirv-to-dxil"
version = "0.2.4"
edition = "2021"
description = "Rust bindings to spirv-to-dxil"
license = "MIT"
repository = "https://github.com/SnowflakePowered/spirv-to-dxil-rs"
keywords = ["SPIR-V", "DXIL"]
readme = "../README.md"
[lib]

[dependencies]
spirv-to-dxil-sys = { version = "0.2", path = "../spirv-to-dxil-sys" }
bitflags = "1.3.2"

[features]
included-bindings = ["spirv-to-dxil-sys/included-bindings"]

[dev-dependencies]
bytemuck = "1.13.0"

[package.metadata.docs.rs]
targets = []
features = ["included-bindings"]
