[package]
name = "spirv-to-dxil"
version = "0.1.1-beta.2"
edition = "2021"
description = "Rust bindings to spirv-to-dxil"
license = "MIT"
repository = "https://github.com/SnowflakePowered/spirv-to-dxil-rs"
keywords = ["SPIR-V", "DXIL"]

[lib]

[dependencies]
spirv-to-dxil-sys = { version = "0.1.1-beta.2", path = "../spirv-to-dxil-sys" }
bitflags = "1.3.2"

[dev-dependencies]
bytemuck = "1.13.0"
