[package]
name = "spirv-to-dxil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
spirv-to-dxil-sys = { version = "0.1.0", path = "../spirv-to-dxil-sys" }
bitflags = "1.3.2"

[dev-dependencies]
bytemuck = "1.13.0"