/* automatically generated by rust-bindgen 0.63.0 */

pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const __bool_true_false_are_defined: u32 = 1;
pub const _VCRT_COMPILER_PREPROCESSOR: u32 = 1;
pub const _SAL_VERSION: u32 = 20;
pub const __SAL_H_VERSION: u32 = 180000000;
pub const _USE_DECLSPECS_FOR_SAL: u32 = 0;
pub const _USE_ATTRIBUTES_FOR_SAL: u32 = 0;
pub const _CRT_PACKING: u32 = 8;
pub const _HAS_EXCEPTIONS: u32 = 1;
pub const _STL_LANG: u32 = 0;
pub const _HAS_CXX17: u32 = 0;
pub const _HAS_CXX20: u32 = 0;
pub const _HAS_CXX23: u32 = 0;
pub const _HAS_NODISCARD: u32 = 0;
pub const WCHAR_MIN: u32 = 0;
pub const WCHAR_MAX: u32 = 65535;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 65535;
pub const DXIL_SPIRV_MAX_VIEWPORT: u32 = 16;
pub const dxil_shader_model_SHADER_MODEL_6_0: dxil_shader_model = 393216;
pub const dxil_shader_model_SHADER_MODEL_6_1: dxil_shader_model = 393217;
pub const dxil_shader_model_SHADER_MODEL_6_2: dxil_shader_model = 393218;
pub const dxil_shader_model_SHADER_MODEL_6_3: dxil_shader_model = 393219;
pub const dxil_shader_model_SHADER_MODEL_6_4: dxil_shader_model = 393220;
pub const dxil_shader_model_SHADER_MODEL_6_5: dxil_shader_model = 393221;
pub const dxil_shader_model_SHADER_MODEL_6_6: dxil_shader_model = 393222;
pub const dxil_shader_model_SHADER_MODEL_6_7: dxil_shader_model = 393223;
pub type dxil_shader_model = ::std::os::raw::c_int;
pub const dxil_validator_version_NO_DXIL_VALIDATION: dxil_validator_version = 0;
pub const dxil_validator_version_DXIL_VALIDATOR_1_0: dxil_validator_version = 65536;
pub const dxil_validator_version_DXIL_VALIDATOR_1_1: dxil_validator_version = 65537;
pub const dxil_validator_version_DXIL_VALIDATOR_1_2: dxil_validator_version = 65538;
pub const dxil_validator_version_DXIL_VALIDATOR_1_3: dxil_validator_version = 65539;
pub const dxil_validator_version_DXIL_VALIDATOR_1_4: dxil_validator_version = 65540;
pub const dxil_validator_version_DXIL_VALIDATOR_1_5: dxil_validator_version = 65541;
pub const dxil_validator_version_DXIL_VALIDATOR_1_6: dxil_validator_version = 65542;
pub const dxil_validator_version_DXIL_VALIDATOR_1_7: dxil_validator_version = 65543;
pub type dxil_validator_version = ::std::os::raw::c_int;
pub type wchar_t = ::std::os::raw::c_ushort;
pub type max_align_t = f64;
pub type va_list = *mut ::std::os::raw::c_char;
extern "C" {
    pub fn __va_start(arg1: *mut *mut ::std::os::raw::c_char, ...);
}
pub type __vcrt_bool = bool;
extern "C" {
    pub fn __security_init_cookie();
}
extern "C" {
    pub fn __security_check_cookie(_StackCookie: usize);
}
extern "C" {
    pub fn __report_gsfailure(_StackCookie: usize) -> !;
}
extern "C" {
    pub static mut __security_cookie: usize;
}
pub type int_least8_t = ::std::os::raw::c_schar;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_longlong;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulonglong;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_int;
pub type int_fast32_t = ::std::os::raw::c_int;
pub type int_fast64_t = ::std::os::raw::c_longlong;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_uint;
pub type uint_fast32_t = ::std::os::raw::c_uint;
pub type uint_fast64_t = ::std::os::raw::c_ulonglong;
pub type intmax_t = ::std::os::raw::c_longlong;
pub type uintmax_t = ::std::os::raw::c_ulonglong;
pub const dxil_spirv_shader_stage_DXIL_SPIRV_SHADER_NONE: dxil_spirv_shader_stage = -1;
pub const dxil_spirv_shader_stage_DXIL_SPIRV_SHADER_VERTEX: dxil_spirv_shader_stage = 0;
pub const dxil_spirv_shader_stage_DXIL_SPIRV_SHADER_TESS_CTRL: dxil_spirv_shader_stage = 1;
pub const dxil_spirv_shader_stage_DXIL_SPIRV_SHADER_TESS_EVAL: dxil_spirv_shader_stage = 2;
pub const dxil_spirv_shader_stage_DXIL_SPIRV_SHADER_GEOMETRY: dxil_spirv_shader_stage = 3;
pub const dxil_spirv_shader_stage_DXIL_SPIRV_SHADER_FRAGMENT: dxil_spirv_shader_stage = 4;
pub const dxil_spirv_shader_stage_DXIL_SPIRV_SHADER_COMPUTE: dxil_spirv_shader_stage = 5;
pub const dxil_spirv_shader_stage_DXIL_SPIRV_SHADER_KERNEL: dxil_spirv_shader_stage = 14;
pub type dxil_spirv_shader_stage = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub union dxil_spirv_const_value {
    pub b: bool,
    pub f32_: f32,
    pub f64_: f64,
    pub i8_: i8,
    pub u8_: u8,
    pub i16_: i16,
    pub u16_: u16,
    pub i32_: i32,
    pub u32_: u32,
    pub i64_: i64,
    pub u64_: u64,
}
#[test]
fn bindgen_test_layout_dxil_spirv_const_value() {
    const UNINIT: ::std::mem::MaybeUninit<dxil_spirv_const_value> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<dxil_spirv_const_value>(),
        8usize,
        concat!("Size of: ", stringify!(dxil_spirv_const_value))
    );
    assert_eq!(
        ::std::mem::align_of::<dxil_spirv_const_value>(),
        8usize,
        concat!("Alignment of ", stringify!(dxil_spirv_const_value))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).b) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_const_value),
            "::",
            stringify!(b)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).f32_) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_const_value),
            "::",
            stringify!(f32_)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).f64_) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_const_value),
            "::",
            stringify!(f64_)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).i8_) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_const_value),
            "::",
            stringify!(i8_)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).u8_) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_const_value),
            "::",
            stringify!(u8_)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).i16_) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_const_value),
            "::",
            stringify!(i16_)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).u16_) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_const_value),
            "::",
            stringify!(u16_)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).i32_) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_const_value),
            "::",
            stringify!(i32_)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).u32_) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_const_value),
            "::",
            stringify!(u32_)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).i64_) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_const_value),
            "::",
            stringify!(i64_)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).u64_) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_const_value),
            "::",
            stringify!(u64_)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct dxil_spirv_specialization {
    pub id: u32,
    pub value: dxil_spirv_const_value,
    pub defined_on_module: bool,
}
#[test]
fn bindgen_test_layout_dxil_spirv_specialization() {
    const UNINIT: ::std::mem::MaybeUninit<dxil_spirv_specialization> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<dxil_spirv_specialization>(),
        24usize,
        concat!("Size of: ", stringify!(dxil_spirv_specialization))
    );
    assert_eq!(
        ::std::mem::align_of::<dxil_spirv_specialization>(),
        8usize,
        concat!("Alignment of ", stringify!(dxil_spirv_specialization))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_specialization),
            "::",
            stringify!(id)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).value) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_specialization),
            "::",
            stringify!(value)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).defined_on_module) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_specialization),
            "::",
            stringify!(defined_on_module)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dxil_spirv_metadata {
    pub requires_runtime_data: bool,
}
#[test]
fn bindgen_test_layout_dxil_spirv_metadata() {
    const UNINIT: ::std::mem::MaybeUninit<dxil_spirv_metadata> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<dxil_spirv_metadata>(),
        1usize,
        concat!("Size of: ", stringify!(dxil_spirv_metadata))
    );
    assert_eq!(
        ::std::mem::align_of::<dxil_spirv_metadata>(),
        1usize,
        concat!("Alignment of ", stringify!(dxil_spirv_metadata))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).requires_runtime_data) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_metadata),
            "::",
            stringify!(requires_runtime_data)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dxil_spirv_object {
    pub metadata: dxil_spirv_metadata,
    pub binary: dxil_spirv_object__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dxil_spirv_object__bindgen_ty_1 {
    pub buffer: *mut ::std::os::raw::c_void,
    pub size: usize,
}
#[test]
fn bindgen_test_layout_dxil_spirv_object__bindgen_ty_1() {
    const UNINIT: ::std::mem::MaybeUninit<dxil_spirv_object__bindgen_ty_1> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<dxil_spirv_object__bindgen_ty_1>(),
        16usize,
        concat!("Size of: ", stringify!(dxil_spirv_object__bindgen_ty_1))
    );
    assert_eq!(
        ::std::mem::align_of::<dxil_spirv_object__bindgen_ty_1>(),
        8usize,
        concat!("Alignment of ", stringify!(dxil_spirv_object__bindgen_ty_1))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).buffer) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_object__bindgen_ty_1),
            "::",
            stringify!(buffer)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_object__bindgen_ty_1),
            "::",
            stringify!(size)
        )
    );
}
#[test]
fn bindgen_test_layout_dxil_spirv_object() {
    const UNINIT: ::std::mem::MaybeUninit<dxil_spirv_object> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<dxil_spirv_object>(),
        24usize,
        concat!("Size of: ", stringify!(dxil_spirv_object))
    );
    assert_eq!(
        ::std::mem::align_of::<dxil_spirv_object>(),
        8usize,
        concat!("Alignment of ", stringify!(dxil_spirv_object))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).metadata) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_object),
            "::",
            stringify!(metadata)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).binary) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_object),
            "::",
            stringify!(binary)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dxil_spirv_compute_runtime_data {
    pub group_count_x: u32,
    pub group_count_y: u32,
    pub group_count_z: u32,
    pub padding0: u32,
    pub base_group_x: u32,
    pub base_group_y: u32,
    pub base_group_z: u32,
}
#[test]
fn bindgen_test_layout_dxil_spirv_compute_runtime_data() {
    const UNINIT: ::std::mem::MaybeUninit<dxil_spirv_compute_runtime_data> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<dxil_spirv_compute_runtime_data>(),
        28usize,
        concat!("Size of: ", stringify!(dxil_spirv_compute_runtime_data))
    );
    assert_eq!(
        ::std::mem::align_of::<dxil_spirv_compute_runtime_data>(),
        4usize,
        concat!("Alignment of ", stringify!(dxil_spirv_compute_runtime_data))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).group_count_x) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_compute_runtime_data),
            "::",
            stringify!(group_count_x)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).group_count_y) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_compute_runtime_data),
            "::",
            stringify!(group_count_y)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).group_count_z) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_compute_runtime_data),
            "::",
            stringify!(group_count_z)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).padding0) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_compute_runtime_data),
            "::",
            stringify!(padding0)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).base_group_x) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_compute_runtime_data),
            "::",
            stringify!(base_group_x)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).base_group_y) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_compute_runtime_data),
            "::",
            stringify!(base_group_y)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).base_group_z) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_compute_runtime_data),
            "::",
            stringify!(base_group_z)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct dxil_spirv_vertex_runtime_data {
    pub first_vertex: u32,
    pub base_instance: u32,
    pub is_indexed_draw: bool,
    pub __bindgen_anon_1: dxil_spirv_vertex_runtime_data__bindgen_ty_1,
    pub draw_id: u32,
    pub viewport_width: f32,
    pub viewport_height: f32,
    pub view_index: u32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union dxil_spirv_vertex_runtime_data__bindgen_ty_1 {
    pub yz_flip_mask: u32,
    pub __bindgen_anon_1: dxil_spirv_vertex_runtime_data__bindgen_ty_1__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dxil_spirv_vertex_runtime_data__bindgen_ty_1__bindgen_ty_1 {
    pub y_flip_mask: u16,
    pub z_flip_mask: u16,
}
#[test]
fn bindgen_test_layout_dxil_spirv_vertex_runtime_data__bindgen_ty_1__bindgen_ty_1() {
    const UNINIT: ::std::mem::MaybeUninit<
        dxil_spirv_vertex_runtime_data__bindgen_ty_1__bindgen_ty_1,
    > = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<dxil_spirv_vertex_runtime_data__bindgen_ty_1__bindgen_ty_1>(),
        4usize,
        concat!(
            "Size of: ",
            stringify!(dxil_spirv_vertex_runtime_data__bindgen_ty_1__bindgen_ty_1)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<dxil_spirv_vertex_runtime_data__bindgen_ty_1__bindgen_ty_1>(),
        2usize,
        concat!(
            "Alignment of ",
            stringify!(dxil_spirv_vertex_runtime_data__bindgen_ty_1__bindgen_ty_1)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).y_flip_mask) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_vertex_runtime_data__bindgen_ty_1__bindgen_ty_1),
            "::",
            stringify!(y_flip_mask)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).z_flip_mask) as usize - ptr as usize },
        2usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_vertex_runtime_data__bindgen_ty_1__bindgen_ty_1),
            "::",
            stringify!(z_flip_mask)
        )
    );
}
#[test]
fn bindgen_test_layout_dxil_spirv_vertex_runtime_data__bindgen_ty_1() {
    const UNINIT: ::std::mem::MaybeUninit<dxil_spirv_vertex_runtime_data__bindgen_ty_1> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<dxil_spirv_vertex_runtime_data__bindgen_ty_1>(),
        4usize,
        concat!(
            "Size of: ",
            stringify!(dxil_spirv_vertex_runtime_data__bindgen_ty_1)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<dxil_spirv_vertex_runtime_data__bindgen_ty_1>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(dxil_spirv_vertex_runtime_data__bindgen_ty_1)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).yz_flip_mask) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_vertex_runtime_data__bindgen_ty_1),
            "::",
            stringify!(yz_flip_mask)
        )
    );
}
#[test]
fn bindgen_test_layout_dxil_spirv_vertex_runtime_data() {
    const UNINIT: ::std::mem::MaybeUninit<dxil_spirv_vertex_runtime_data> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<dxil_spirv_vertex_runtime_data>(),
        32usize,
        concat!("Size of: ", stringify!(dxil_spirv_vertex_runtime_data))
    );
    assert_eq!(
        ::std::mem::align_of::<dxil_spirv_vertex_runtime_data>(),
        4usize,
        concat!("Alignment of ", stringify!(dxil_spirv_vertex_runtime_data))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).first_vertex) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_vertex_runtime_data),
            "::",
            stringify!(first_vertex)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).base_instance) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_vertex_runtime_data),
            "::",
            stringify!(base_instance)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).is_indexed_draw) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_vertex_runtime_data),
            "::",
            stringify!(is_indexed_draw)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).draw_id) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_vertex_runtime_data),
            "::",
            stringify!(draw_id)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).viewport_width) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_vertex_runtime_data),
            "::",
            stringify!(viewport_width)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).viewport_height) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_vertex_runtime_data),
            "::",
            stringify!(viewport_height)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).view_index) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_vertex_runtime_data),
            "::",
            stringify!(view_index)
        )
    );
}
pub const dxil_spirv_yz_flip_mode_DXIL_SPIRV_YZ_FLIP_NONE: dxil_spirv_yz_flip_mode = 0;
pub const dxil_spirv_yz_flip_mode_DXIL_SPIRV_Y_FLIP_UNCONDITIONAL: dxil_spirv_yz_flip_mode = 1;
pub const dxil_spirv_yz_flip_mode_DXIL_SPIRV_Z_FLIP_UNCONDITIONAL: dxil_spirv_yz_flip_mode = 2;
pub const dxil_spirv_yz_flip_mode_DXIL_SPIRV_YZ_FLIP_UNCONDITIONAL: dxil_spirv_yz_flip_mode = 3;
pub const dxil_spirv_yz_flip_mode_DXIL_SPIRV_Y_FLIP_CONDITIONAL: dxil_spirv_yz_flip_mode = 4;
pub const dxil_spirv_yz_flip_mode_DXIL_SPIRV_Z_FLIP_CONDITIONAL: dxil_spirv_yz_flip_mode = 8;
pub const dxil_spirv_yz_flip_mode_DXIL_SPIRV_YZ_FLIP_CONDITIONAL: dxil_spirv_yz_flip_mode = 12;
pub type dxil_spirv_yz_flip_mode = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dxil_spirv_runtime_conf {
    pub runtime_data_cbv: dxil_spirv_runtime_conf__bindgen_ty_1,
    pub push_constant_cbv: dxil_spirv_runtime_conf__bindgen_ty_2,
    pub zero_based_vertex_instance_id: bool,
    pub zero_based_compute_workgroup_id: bool,
    pub yz_flip: dxil_spirv_runtime_conf__bindgen_ty_3,
    pub read_only_images_as_srvs: bool,
    pub force_sample_rate_shading: bool,
    pub lower_view_index: bool,
    pub lower_view_index_to_rt_layer: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dxil_spirv_runtime_conf__bindgen_ty_1 {
    pub register_space: u32,
    pub base_shader_register: u32,
}
#[test]
fn bindgen_test_layout_dxil_spirv_runtime_conf__bindgen_ty_1() {
    const UNINIT: ::std::mem::MaybeUninit<dxil_spirv_runtime_conf__bindgen_ty_1> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<dxil_spirv_runtime_conf__bindgen_ty_1>(),
        8usize,
        concat!(
            "Size of: ",
            stringify!(dxil_spirv_runtime_conf__bindgen_ty_1)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<dxil_spirv_runtime_conf__bindgen_ty_1>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(dxil_spirv_runtime_conf__bindgen_ty_1)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).register_space) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_runtime_conf__bindgen_ty_1),
            "::",
            stringify!(register_space)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).base_shader_register) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_runtime_conf__bindgen_ty_1),
            "::",
            stringify!(base_shader_register)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dxil_spirv_runtime_conf__bindgen_ty_2 {
    pub register_space: u32,
    pub base_shader_register: u32,
}
#[test]
fn bindgen_test_layout_dxil_spirv_runtime_conf__bindgen_ty_2() {
    const UNINIT: ::std::mem::MaybeUninit<dxil_spirv_runtime_conf__bindgen_ty_2> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<dxil_spirv_runtime_conf__bindgen_ty_2>(),
        8usize,
        concat!(
            "Size of: ",
            stringify!(dxil_spirv_runtime_conf__bindgen_ty_2)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<dxil_spirv_runtime_conf__bindgen_ty_2>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(dxil_spirv_runtime_conf__bindgen_ty_2)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).register_space) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_runtime_conf__bindgen_ty_2),
            "::",
            stringify!(register_space)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).base_shader_register) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_runtime_conf__bindgen_ty_2),
            "::",
            stringify!(base_shader_register)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dxil_spirv_runtime_conf__bindgen_ty_3 {
    pub mode: dxil_spirv_yz_flip_mode,
    pub y_mask: u16,
    pub z_mask: u16,
}
#[test]
fn bindgen_test_layout_dxil_spirv_runtime_conf__bindgen_ty_3() {
    const UNINIT: ::std::mem::MaybeUninit<dxil_spirv_runtime_conf__bindgen_ty_3> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<dxil_spirv_runtime_conf__bindgen_ty_3>(),
        8usize,
        concat!(
            "Size of: ",
            stringify!(dxil_spirv_runtime_conf__bindgen_ty_3)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<dxil_spirv_runtime_conf__bindgen_ty_3>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(dxil_spirv_runtime_conf__bindgen_ty_3)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mode) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_runtime_conf__bindgen_ty_3),
            "::",
            stringify!(mode)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).y_mask) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_runtime_conf__bindgen_ty_3),
            "::",
            stringify!(y_mask)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).z_mask) as usize - ptr as usize },
        6usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_runtime_conf__bindgen_ty_3),
            "::",
            stringify!(z_mask)
        )
    );
}
#[test]
fn bindgen_test_layout_dxil_spirv_runtime_conf() {
    const UNINIT: ::std::mem::MaybeUninit<dxil_spirv_runtime_conf> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<dxil_spirv_runtime_conf>(),
        32usize,
        concat!("Size of: ", stringify!(dxil_spirv_runtime_conf))
    );
    assert_eq!(
        ::std::mem::align_of::<dxil_spirv_runtime_conf>(),
        4usize,
        concat!("Alignment of ", stringify!(dxil_spirv_runtime_conf))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).runtime_data_cbv) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_runtime_conf),
            "::",
            stringify!(runtime_data_cbv)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).push_constant_cbv) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_runtime_conf),
            "::",
            stringify!(push_constant_cbv)
        )
    );
    assert_eq!(
        unsafe {
            ::std::ptr::addr_of!((*ptr).zero_based_vertex_instance_id) as usize - ptr as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_runtime_conf),
            "::",
            stringify!(zero_based_vertex_instance_id)
        )
    );
    assert_eq!(
        unsafe {
            ::std::ptr::addr_of!((*ptr).zero_based_compute_workgroup_id) as usize - ptr as usize
        },
        17usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_runtime_conf),
            "::",
            stringify!(zero_based_compute_workgroup_id)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).yz_flip) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_runtime_conf),
            "::",
            stringify!(yz_flip)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).read_only_images_as_srvs) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_runtime_conf),
            "::",
            stringify!(read_only_images_as_srvs)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).force_sample_rate_shading) as usize - ptr as usize },
        29usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_runtime_conf),
            "::",
            stringify!(force_sample_rate_shading)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).lower_view_index) as usize - ptr as usize },
        30usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_runtime_conf),
            "::",
            stringify!(lower_view_index)
        )
    );
    assert_eq!(
        unsafe {
            ::std::ptr::addr_of!((*ptr).lower_view_index_to_rt_layer) as usize - ptr as usize
        },
        31usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_runtime_conf),
            "::",
            stringify!(lower_view_index_to_rt_layer)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dxil_spirv_debug_options {
    pub dump_nir: bool,
}
#[test]
fn bindgen_test_layout_dxil_spirv_debug_options() {
    const UNINIT: ::std::mem::MaybeUninit<dxil_spirv_debug_options> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<dxil_spirv_debug_options>(),
        1usize,
        concat!("Size of: ", stringify!(dxil_spirv_debug_options))
    );
    assert_eq!(
        ::std::mem::align_of::<dxil_spirv_debug_options>(),
        1usize,
        concat!("Alignment of ", stringify!(dxil_spirv_debug_options))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).dump_nir) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_debug_options),
            "::",
            stringify!(dump_nir)
        )
    );
}
pub type dxil_spirv_msg_callback = ::std::option::Option<
    unsafe extern "C" fn(priv_: *mut ::std::os::raw::c_void, msg: *const ::std::os::raw::c_char),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dxil_spirv_logger {
    pub priv_: *mut ::std::os::raw::c_void,
    pub log: dxil_spirv_msg_callback,
}
#[test]
fn bindgen_test_layout_dxil_spirv_logger() {
    const UNINIT: ::std::mem::MaybeUninit<dxil_spirv_logger> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<dxil_spirv_logger>(),
        16usize,
        concat!("Size of: ", stringify!(dxil_spirv_logger))
    );
    assert_eq!(
        ::std::mem::align_of::<dxil_spirv_logger>(),
        8usize,
        concat!("Alignment of ", stringify!(dxil_spirv_logger))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).priv_) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_logger),
            "::",
            stringify!(priv_)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).log) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(dxil_spirv_logger),
            "::",
            stringify!(log)
        )
    );
}
extern "C" {
    pub fn spirv_to_dxil(
        words: *const u32,
        word_count: usize,
        specializations: *mut dxil_spirv_specialization,
        num_specializations: ::std::os::raw::c_uint,
        stage: dxil_spirv_shader_stage,
        entry_point_name: *const ::std::os::raw::c_char,
        shader_model_max: dxil_shader_model,
        validator_version_max: dxil_validator_version,
        debug_options: *const dxil_spirv_debug_options,
        conf: *const dxil_spirv_runtime_conf,
        logger: *const dxil_spirv_logger,
        out_dxil: *mut dxil_spirv_object,
    ) -> bool;
}
extern "C" {
    pub fn spirv_to_dxil_free(dxil: *mut dxil_spirv_object);
}
extern "C" {
    pub fn spirv_to_dxil_get_version() -> u64;
}
